# Generated by Django 4.1.3 on 2022-12-03 11:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=30)),
                ("post_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("lng", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("lat", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField(max_length=1000)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["name", "content", "address"],
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wishes.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WIshListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("approved", models.BooleanField(default=False)),
                (
                    "wish_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishes.wishlist",
                    ),
                ),
            ],
        ),
    ]
